/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Phone.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'




export function Model(props) {


  const group = useRef();

  const texture = useTexture({
    Cel: '3d/gltf/Cel.jpg',
    Camara: '3d/gltf/Camara.jpg',
    Blanco : '3d/gltf/Blanco.jpg',
    Emission : '3d/gltf/Emission.jpg',
  })


  const { nodes, materials } = useGLTF('/3d/gltf/Phone.gltf')


  return (
    <group {...props} ref={group} dispose={null}>
      <group position={[-0.056, 0.339, 0.147]} rotation={[-0.228, -0.438, 0.205]} scale={[1, 1.161, 1]}>
        <mesh geometry={nodes.objMesh_1.geometry} material={materials.Cel} texture={texture.Cel} />
        <mesh geometry={nodes.objMesh_2.geometry} material={materials.Camara} texture={texture.Camara}/>
        <mesh geometry={nodes.objMesh_3.geometry} material={materials.Blanco} texture={texture.Blanco}/>
        <mesh geometry={nodes.objMesh_4.geometry} material={materials.Emission} texture={texture.Emission} />
      </group>
    </group>
  )
}

useGLTF.preload('/Phone.gltf')
