/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Android.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useTexture } from '@react-three/drei';


export function Model(props) {
  const { nodes, materials } = useGLTF('/3d/android/android.glb')

  
    // const texture = useTexture('/3d/android/android.glb')
    // const [texture1, texture2] = useTexture([texture1, texture2])

  return (
    <group {...props} dispose={null}>
      <group position={[-0.001, 0.193, -0.001]} rotation={[0, Math.PI / 2, 0]} scale={0.1}>
        <mesh geometry={nodes.objMesh_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.objMesh_2.geometry} material={materials.None} />
        <mesh geometry={nodes.objMesh_3.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/android/android.glb')
